### PR TITLE
fix web dependency configuration, perspective module config, add integration notes to web readme

### LINKED ISSUE #93: Example perspective module does not work in  8.1.21
## java version:
``` bash
$ java --version
Picked up JAVA_TOOL_OPTIONS: -agentpath:"C:\WINDOWS\system32\Aternity\Java\JavaHookLoader.dll"="C:\ProgramData\Aternity\hooks"
openjdk 11.0.16.1 2022-08-12
OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (build 11.0.16.1+1, mixed mode)
```

## steps to replicate
- clones head
- runs gradlew zipModule (output looks correct, compared to the pre kotlin change)
- uses the module signing tool
- installs the module in ignition
- receives the following error:

> ModuleManager | 31Oct2022 20:04:35 | Error starting module org.fakester.radcomponent

``` none
java.lang.NoClassDefFoundError: com/inductiveautomation/perspective/gateway/api/PerspectiveContext
at org.fakester.gateway.RadGatewayHook.startup(RadGatewayHook.java:39)
at com.inductiveautomation.ignition.gateway.modules.ModuleManagerImpl$LoadedModule.startup(ModuleManagerImpl.java:2439)
at com.inductiveautomation.ignition.gateway.modules.ModuleManagerImpl.startupModule(ModuleManagerImpl.java:1232)
at com.inductiveautomation.ignition.gateway.modules.ModuleManagerImpl$2.call(ModuleManagerImpl.java:777)
at com.inductiveautomation.ignition.gateway.modules.ModuleManagerImpl.executeModuleOperation(ModuleManagerImpl.java:953)
at com.inductiveautomation.ignition.gateway.modules.ModuleManagerImpl.installModuleInternal(ModuleManagerImpl.java:743)
at com.inductiveautomation.ignition.gateway.modules.ModuleManagerImpl$InstallCommand.execute(ModuleManagerImpl.java:1909)
at com.inductiveautomation.ignition.gateway.modules.ModuleManagerImpl$Receiver.receiveCall(ModuleManagerImpl.java:1862)
at com.inductiveautomation.ignition.gateway.redundancy.QueueableMessageReceiver.receiveCall(QueueableMessageReceiver.java:47)
at com.inductiveautomation.ignition.gateway.redundancy.RedundancyManagerImpl.dispatchMessage(RedundancyManagerImpl.java:1007)
at com.inductiveautomation.ignition.gateway.redundancy.RedundancyManagerImpl$ExecuteTask.run(RedundancyManagerImpl.java:1075)
at com.inductiveautomation.ignition.common.execution.impl.BasicExecutionEngine$ThrowableCatchingRunnable.run(BasicExecutionEngine.java:544)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.inductiveautomation.perspective.gateway.api.PerspectiveContext
at java.base/java.net.URLClassLoader.findClass(Unknown Source)
at com.inductiveautomation.ignition.gateway.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:37)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
at com.inductiveautomation.ignition.gateway.modules.ModuleClassLoader.loadClass(ModuleClassLoader.java:85)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
... 18 common frames omitted
```

### PR DESCRIPTION
**Pull request by PerryAJ**
Fixes #93 

Two different issues identified:

1. The primary issue when loading the module was due to improperly set perspective module dependency configuration.  

2. The web project did seem to build correctly for me, but was not properly getting included into the assembled module

In addition, I added some documentation to explain the change in how the web assets are integrated into the project.

Contrary to the original changes, I checked this fix in completely clean checkout and it successfully loaded into an 8.1.22 gateway.

### CODE REVIEW

File: perspective-component/README.md [hunk 1]
```diff
@@ -143,6 +144,7 @@ Within the `web` directory is a _lerna workspace_, which is simply a javascript
   └── web                                 // parent directory for the web assets we build
       ├── README.md
       ├── build.gradle
```
Comment (thirdgen88) [inline perspective-component/README.md:146]: Might as well remove this `build.gradle` from the tree here, and also convert the other `build.gradle` mentions above to `build.gradle.kts`.

**Review by thirdgen88 — COMMENTED** [review]
I like the added documentation, gives a good explanation for the structural aspects. 👍

**Review by thirdgen88 — APPROVED** [review]

**Comment by bradder555** [comment]
I tested this on my environment and it worked, LGTM
